// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbo: typeof import('element-plus/es')['ElCheckbo']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    TodoBody: typeof import('./src/components/TodoBody.vue')['default']
    TodoFooter: typeof import('./src/components/TodoFooter.vue')['default']
    TodoHeader: typeof import('./src/components/TodoHeader.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}
